const gulp   = require('gulp'),
      closureCompiler = require('google-closure-compiler').gulp(),
      gulpDPZ = require('../../../gulp-diamond-princess-zoning/index.js'),
      fs     = require( 'fs' );

gulp.task( 'dist', gulp.series(
  function(){
      return gulp.src(
          [
            './src.js/**/*.js'
          ]
      ).pipe(
          gulpDPZ(
              {
                  labelGlobal        : 'global',
                  labelPackageGlobal : 'packageGlobal',
                  labelModuleGlobal  : 'moduleGlobal',
                  packageGlobalArgs  : [ 'Math,Infinity,undefined', 'Math,1/0,void 0' ],
                  basePath           : './',
                  // wrapAll            : true
              }
          )
      ).pipe(
          closureCompiler(
              {
                externs           : [ './src.externs/externs.generated.js' ],
                define            : [
                    'DEFINE_REGEXP_COMPAT__DEBUG=false',
                    'DEFINE_REGEXP_COMPAT__MINIFY=true',
                    'DEFINE_REGEXP_COMPAT__NODEJS=false',
                    'DEFINE_REGEXP_COMPAT__ES2018=false'
                ],
                compilation_level : 'ADVANCED',
                // compilation_level : 'WHITESPACE_ONLY',
                env               : 'CUSTOM',
                // formatting        : 'PRETTY_PRINT',
                warning_level     : 'VERBOSE',
                language_in       : 'ECMASCRIPT3',
                language_out      : 'ECMASCRIPT3',
                // output_wrapper    : '(function(){\n%output%\n})()',
                js_output_file    : 'rerejs-es3.min.js'
              }
          )
      ).pipe( gulp.dest( 'dist' ) );
  }
) );

const dontEditMessage = '// THIS SCRIPT IS GENERATED BY "##". DO NOT EDIT!\n\n';

gulp.task( 'data', gulp.series(
    function( cb ){ // Case folding
        var fileName = './tools.js/1_generateUnicodeFoldMap.js';

        fs.writeFileSync(
            './src.js/3_data.generated/1_unicodeFoldMap.generated.js',
            dontEditMessage.replace( '##', fileName ) + require( fileName )()
        );
        cb();
    },
    function( cb ){ // Case folding Legacy
        var fileName = './tools.js/2_generateUnicodeFoldMapLegacy.js';

        fs.writeFileSync(
            './src.js/3_data.generated/2_unicodeFoldMapLegacy.generated.js',
            dontEditMessage.replace( '##', fileName ) + require( fileName )()
        );
        cb();
    },
    function( cb ){ // Unicode Category
      var fileName = './tools.js/3_generateUnicodeCategory.js';

      fs.writeFileSync(
          './src.js/3_data.generated/3_unicodeCategory.generated.js',
          dontEditMessage.replace( '##', fileName ) + require( fileName )()
      );
      cb();
    },
    function( cb ){ // Unicode Property
        var fileName = './tools.js/4_generateUnicodeProperty.js';

        fs.writeFileSync(
            './src.js/3_data.generated/4_unicodeProperty.generated.js',
            dontEditMessage.replace( '##', fileName ) + require( fileName )()
        );
        cb();
    },
    function( cb ){ // Unicode Property Alias
      var fileName = './tools.js/5_generateUnicodePropertyAlias.js';

      fs.writeFileSync(
          './src.js/3_data.generated/5_unicodePropertyAlias.generated.js',
          dontEditMessage.replace( '##', fileName ) + require( fileName )()
      );
      cb();
    },
    function( cb ){ // Unicode Property Value Alias
        var fileName = './tools.js/6_generateUnicodePropertyValueAlias.js';

        fs.writeFileSync(
            './src.js/3_data.generated/6_unicodePropertyValueAlias.generated.js',
            dontEditMessage.replace( '##', fileName ) + require( fileName )()
        );
        cb();
    },
    function( cb ){ // Unicode Script
        var fileName = './tools.js/7_generateUnicodeScript.js';

        fs.writeFileSync(
            './src.js/3_data.generated/7_unicodeScript.generated.js',
            dontEditMessage.replace( '##', fileName ) + require( fileName )()
        );
        cb();
    },
    function( cb ){
        var fileName = './tools.js/8_generateCharSetWordAndUnicodeWord.js';

        fs.writeFileSync(
            './src.js/4_char-class/3_ascii.generated.js',
            dontEditMessage.replace( '##', fileName ) + require( fileName )()
        );
        cb();
    },
    function( cb ){
        var fileName = './tools.js/9_generateCharSetIdStartAndIdContinue';

        fs.writeFileSync(
          './src.js/5_syntax/3_charSetIdStartAndIdContinue.generated.js',
            dontEditMessage.replace( '##', fileName ) + require( fileName )()
        );
        cb();
    },
    function( cb ){
        var fileName = './tools.js/A_generateExterns.js';

        fs.writeFileSync(
            './src.externs/externs.generated.js',
            dontEditMessage.replace( '##', fileName ) + require( fileName )()
        );
        cb();
    }
) );
