var /** @define {boolean} */
    DEFINE_REGEXP_COMPAT__DEBUG  = true,
    /** @define {boolean} */
    DEFINE_REGEXP_COMPAT__MINIFY = false,
    /** @define {boolean} */
    DEFINE_REGEXP_COMPAT__NODEJS = true,
    /** @define {number} */
    DEFINE_REGEXP_COMPAT__CLIENT_MIN_ES_VERSION =    2, // 2, 3, 5, 6(2015), 2018
    /** @define {number} */
    DEFINE_REGEXP_COMPAT__ES_FEATURE_VERSION    = 2018, //    3, 5, 6(2015), 2018

    /** @define {boolean} */
    DEFINE_REGEXP_COMPAT__EXPORT_BY_RETURN            = false,
    /** @define {boolean} */
    DEFINE_REGEXP_COMPAT__EXPORT_BY_CALL_REGEXPCOMPAT = false;

if(
   !DEFINE_REGEXP_COMPAT__NODEJS &&
    DEFINE_REGEXP_COMPAT__CLIENT_MIN_ES_VERSION !== 2 &&
    DEFINE_REGEXP_COMPAT__CLIENT_MIN_ES_VERSION !== 3 &&
    DEFINE_REGEXP_COMPAT__CLIENT_MIN_ES_VERSION !== 5 &&
    DEFINE_REGEXP_COMPAT__CLIENT_MIN_ES_VERSION !== 6 &&
    DEFINE_REGEXP_COMPAT__CLIENT_MIN_ES_VERSION !== 2015 &&
    DEFINE_REGEXP_COMPAT__CLIENT_MIN_ES_VERSION !== 2018
){
      throw 'Invalid DEFINE_REGEXP_COMPAT__CLIENT_MIN_ES_VERSION(=2|3|5|6|2015|2018) value! ' + DEFINE_REGEXP_COMPAT__CLIENT_MIN_ES_VERSION;
};

if( 
    DEFINE_REGEXP_COMPAT__ES_FEATURE_VERSION !== 3 &&
    DEFINE_REGEXP_COMPAT__ES_FEATURE_VERSION !== 5 &&
    DEFINE_REGEXP_COMPAT__ES_FEATURE_VERSION !== 6 &&
    DEFINE_REGEXP_COMPAT__ES_FEATURE_VERSION !== 2015 &&
    DEFINE_REGEXP_COMPAT__ES_FEATURE_VERSION !== 2018
){
    throw 'Invalid DEFINE_REGEXP_COMPAT__ES_FEATURE_VERSION(=3|5|6|2015|2018) value! ' + DEFINE_REGEXP_COMPAT__ES_FEATURE_VERSION;
};
